name: Tests

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[asgi-file-uploads]
        pip install -r requirements-dev.txt
    - name: Pytest
      run: |
        pytest --cov=ariadne --cov=tests
    - uses: codecov/codecov-action@v1
    - name: Linters
      run: |
        pylint ariadne tests setup.py
        mypy ariadne --ignore-missing-imports --check-untyped-defs
        black --check .
